---
- name: using Variables
  hosts: all
  become: yes
  vars:
   package: apache2
   user_allowded: true
   
   tasks:
    - name: We are uninstalling "{{package}}"
      apt:
       name: "{{package}}"
       state: absent
    - name: should not present "{{package}}"
      service:
       name: apache2
       state: stopped 
