---
- name: create new file and delete it.
  hosts: all
  tasks:
   - name: create username file in tmp directory
     file:
       path: '/tmp/deepak1.txt'
       state: touch
   - name: copy host file to every node
     copy:
      src: '/etc/ansible/hosts'
      dest: '/tmp'
