---
- name : install httpd packages and perform git config
  hosts: all
  become: yes
  tasks:
   - name: install apache httpd
     apt: 
      name: apache2
      state: present
   - name: Read all values from git config
     community.general.git_config:
      list_all: yes
      scope: global
    
    
     
